/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:cf27b692-ba47-4d4a-86b6-9b4ed5630750",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_O2jEI6eq3",
    "aws_user_pools_web_client_id": "629qlgi2cnmtu774osis56d77r",
    "oauth": {}
};


export default awsmobile;
